const discs_list = [{
        img: "./img/psd-mockup.jpg",
        name: "PSD mockup",
        prise: "$94.00",
        sale: false,
        sale_prise: false,
    },
    {
        img: "./img/songs-about-jane.jpg",
        name: "Songs about Jane",
        prise: "$132.00",
        sale: "12% OFF",
        sale_prise: "$145.00",
    },
    {
        img: "./img/everything-in-transit.jpg",
        name: "Everything In Transit",
        prise: "$215.00",
        sale: false,
        sale_prise: false,
    },
    {
        img: "./img/the-waves-bloom.jpg",
        name: "The Waves Bloom",
        prise: "$115.00",
        sale: "20% OFF",
        sale_prise: "$145.00",
    },
    {
        img: "./img/dark-monolith.jpg",
        name: "Dark Monolith",
        prise: "$231.00",
        sale: false,
        sale_prise: false,
    },
    {
        img: "./img/neon-ink.png",
        name: "Neon Ink",
        prise: "121.00",
        sale: false,
        sale_prise: false,
    },
    {
        img: "./img/the-dkng-snow.jpg",
        name: "THE DKNG SNOW",
        prise: "$200.00",
        sale: "20% OFF",
        sale_prise: "$250.00",
    },
    {
        img: "./img/atoms-for-peace.jpg",
        name: "Atoms For Peace",
        prise: "$89.00",
        sale: false,
        sale_prise: false,
    },

    {
        img: "./img/m.jpg",
        name: "M",
        prise: "$130.00",
        sale: false,
        sale_prise: "false",
    },
    {
        img: "./img/back-to-us.png",
        name: "Back To US",
        prise: "$220.00",
        sale: false,
        sale_prise: "false",
    },
    {
        img: "./img/psyche-delic.jpg",
        name: "Psyche Delic",
        prise: "$120.00",
        sale: false,
        sale_prise: "false",
    },
    {
        img: "./img/black.jpg",
        name: "Black",
        prise: "$320.00",
        sale: false,
        sale_prise: "false",
    },
    {
        img: "./img/ren.jpg",
        name: "REN",
        prise: "$230.00",
        sale: false,
        sale_prise: "false",
    },
    {
        img: "./img/bad-blood.jpg",
        name: "Bad Blood",
        prise: "$124.00",
        sale: false,
        sale_prise: "false",
    },
    {
        img: "./img/night.jpg",
        name: "Night",
        prise: "$241.00",
        sale: "12% OFF",
        sale_prise: "$272.00",
    },
];